### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by bookerthegeek** [TheLMiffy1111/JAOPCA#52] opened 2018-03-04 06:29 UTC
## Heyo! ##
Say this in the logs, thought you should know. Does not cause a crash.

```
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: java.lang.ClassNotFoundException: erogenousbeef.bigreactors.init.InitHandler
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at java.lang.Class.forName0(Native Method)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at java.lang.Class.forName(Unknown Source)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at thelm.oredictinit.compat.CompatExtremeReactors.register(CompatExtremeReactors.java:19)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at thelm.oredictinit.registry.OreDictRegisCore.initCompat(OreDictRegisCore.java:18)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at thelm.oredictinit.lib.EventHandler.onRegistryWrapUp(EventHandler.java:24)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1326_EventHandler_onRegistryWrapUp_Event0.invoke(.dynamic)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at thelm.wrapup.WrapUp.onVillagerProfessionRegisterLowest(WrapUp.java:97)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_456_WrapUp_onVillagerProfessionRegisterLowest_Register.invoke(.dynamic)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:746)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[22:01:22] [main/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[22:01:22] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NullPointerException
```

### Versions ###
forge-1.12.2-14.23.2.2618-universal.jar
ExtremeReactors-1.12.2-0.4.5.46
JAOPCA-1.12.2-2.2.6.77

**Comment by TheLMiffy1111** [comment] 2018-03-04 07:30
Duplicate of #44

**Closed as completed** 2018-03-04 07:30 UTC
Labels: duplicate
