### ISSUE TITLE
[1.16.4]JAOPCA and Thermal Smeltery Server issues?

### ISSUE THREAD

**Issue by Algester** [TheLMiffy1111/JAOPCA#184] opened 2020-12-26 11:13 UTC
https://pastebin.com/Yvm0uYqj

I'm still trying to debug this if I have other mods doing quirky things...

**Comment by Algester** [comment] 2020-12-26 14:35
It maybe because at this point some of the recipes have depreciated (enderium's recipe has been changed for example) that might be causing some issues if not Thermal has changed a few API calls

**Comment by TheLMiffy1111** [comment] 2020-12-27 14:18
Duplicate of #182 , already fixed, please update JAOPCA.

**Closed as completed by TheLMiffy1111** 2020-12-27 14:18 UTC
Labels: duplicate
