### ISSUE TITLE
Add recipes?

### ISSUE THREAD

**Issue by Trinsdar** [TheLMiffy1111/JAOPCA#32] opened 2017-09-13 18:36 UTC
When mekinism, thermal foundation, and joapca are installed, joacpa adds mithril, platinum and such crystals and slurry and other parts, but does not actually add the recipes. And since modtweaker does not support mekinism in 1.10, I can't add the recipes myself. 

I am using:
JAOPCA-1.10.2-2.0.2.42
jei_1.10.2-3.14.7.416
Mekanism-1.10.2-9.2.3.97
ThermalExpansion-1.10.2-5.1.10.25-universal
ThermalFoundation-1.10.2-2.1.5.12-universal

**Comment by TheLMiffy1111** [comment] 2017-09-14 01:18
Mekanism and JEI issue.
Duplicate of #10.

**Comment by thiakil** [comment] 2017-09-19 01:21
@TheLMiffy1111 nope, this is your issue. On 1.10 the MODID for Mekanism is `Mekanism`, you are using `mekanism` @ https://github.com/TheLMiffy1111/JAOPCA/blob/1.10/src/main/java/thelm/jaopca/modules/ModuleMekanism.java#L195 and other helpers

**Comment by TheLMiffy1111** [comment] 2017-09-19 04:08
ah ok sorry

**Closed as completed** 2017-10-08 01:56 UTC
Labels: bug
