### ISSUE TITLE
[1.12] Crash when loading the game

### ISSUE THREAD

**Issue by Migmag789** [TheLMiffy1111/JAOPCA#138] opened 2019-09-22 12:34 UTC
Hey ! I was simply loading my modpack, but then the game crashed during loading. Here's the crash report : https://paste.dimdev.org/ifudugivef.mccrash
Thanks for your great mod !

**Comment by TheLMiffy1111** [comment] 2019-09-22 13:52
Duplicate of #128

**Closed as completed by TheLMiffy1111** 2019-09-22 13:52 UTC
