### ISSUE TITLE
[bug] Galacticraft's Titanium not working

### ISSUE THREAD

**Issue by Mike-U5** [TheLMiffy1111/JAOPCA#61] opened 2018-04-21 14:59 UTC
The mod will not generate any items for Titanium from GalacticraftPlanets.
Titanium Ingots are in the oredictionary as ingotTitanium. GalacticraftPlanets also uses Desh, but that appears to work fine.

Titanium does not have an ore, but I set **ingot_oreless** to **true** in the config file but it still doesn't work. However, Meteoric Iron does work even though this is also oreless and from Galacticraft.

**Used Versions:**
Forge 14.23.2.2637
JAOPCA-1.12.2-2.2.6.81
Galacticraft-1.12.2-4.0.1.174

**Comment by EngineerXL** [comment] 2018-07-06 04:32
I think, that it's not an issue, beauce GalactiCraft has ilmenite ore, so... it can be registered as ore:TitaniumOre

**Comment by TheLMiffy1111** [comment] 2019-04-03 14:32
duplicate of #48

**Closed as completed** 2019-04-03 14:32 UTC
