### ISSUE TITLE
crash with ic2

### ISSUE THREAD

**Issue by Akay1500** [TheLMiffy1111/JAOPCA#137] opened 2019-09-11 12:42 UTC
i am not sure but did another mod change the block of air to something else ? idk what wrapup has to do with it . i need help
coremods are present:
  ToolProgressionPlugin (toolprogression-core-1.12.2-1.6.6.jar)
  RandomPatches (randompatches-1.12.2-1.17.1.0.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  CorePlugin (SmoothFont-mc1.12.2-2.0.jar)
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.3.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.5.0-139-universal.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.19.2-release.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  SmoothWaterCore (SmoothWater-0.1.4.jar)
  HCASM (HammerCore-1.12.2-2.0.5.0.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  Quark Plugin (Quark-r1.5-166.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.68-core.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.2.7.1.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.6-core.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.229.jar)
  ForgelinPlugin (Forgelin-1.8.3.jar)
  Plugin (NotEnoughIDs-1.5.4.4.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  MekanismCoremod (Mekanism-1.12.2-9.7.9.380.jar)
  AstralCore (astralsorcery-1.12.2-1.10.19.jar)
  LoadingPlugin (Reskillable-1.12.2-1.12.5.jar)
  Botania Tweaks Core (botaniatweaks-1.8.6.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.2.0.jar)
  weaponlib (mw-1.11.7.7_mc1.12.2.jar)
  TNTUtilities Core (tnt_utilities-mc1.12-1.2.3.jar)
  PluginLoader (MemoryTester-0.4.2.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 9/10/19 11:27 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from WrapUp (wrapup)
Caused by: java.lang.RuntimeException: The output ItemStack 1xtile.air@0 is invalid.
	at ic2.core.recipe.BasicMachineRecipeManager.displayError(BasicMachineRecipeManager.java:164)
	at ic2.core.recipe.BasicMachineRecipeManager.addRecipe(BasicMachineRecipeManager.java:60)
	at ic2.core.recipe.BasicMachineRecipeManager.addRecipe(BasicMachineRecipeManager.java:47)
	at thelm.jaopca.modules.ModuleIndustrialCraft.addCompressorRecipe(ModuleIndustrialCraft.java:120)
	at thelm.jaopca.modules.ModuleTinyDust.init(ModuleTinyDust.java:105)
	at thelm.jaopca.registry.RegistryCore.registerInit(RegistryCore.java:407)
	at thelm.jaopca.registry.RegistryCore.init(RegistryCore.java:83)
	at thelm.jaopca.utils.JAOPCAEventHandler.onInitWrapUp(JAOPCAEventHandler.java:38)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2986_JAOPCAEventHandler_onInitWrapUp_Event2.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at thelm.wrapup.WrapUp.secondMovement(WrapUp.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by asd0210a** [comment] 2020-06-21 13:18
same.
https://pastebin.com/tK1vidxn

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 6/21/20 6:16 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from WrapUp (wrapup)
Caused by: java.lang.RuntimeException: The output ItemStack 1xtile.air@0 is invalid.
	at ic2.core.recipe.BasicMachineRecipeManager.displayError(BasicMachineRecipeManager.java:164)
	at ic2.core.recipe.BasicMachineRecipeManager.addRecipe(BasicMachineRecipeManager.java:60)
	at ic2.core.recipe.BasicMachineRecipeManager.addRecipe(BasicMachineRecipeManager.java:47)
	at thelm.jaopca.modules.ModuleIndustrialCraft.addCompressorRecipe(ModuleIndustrialCraft.java:120)
	at thelm.jaopca.modules.ModuleTinyDust.init(ModuleTinyDust.java:105)
	at thelm.jaopca.registry.RegistryCore.registerInit(RegistryCore.java:407)
	at thelm.jaopca.registry.RegistryCore.init(RegistryCore.java:83)
	at thelm.jaopca.utils.JAOPCAEventHandler.onInitWrapUp(JAOPCAEventHandler.java:38)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_588_JAOPCAEventHandler_onInitWrapUp_Event2.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at thelm.wrapup.WrapUp.secondMovement(WrapUp.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1132583352 bytes (1080 MB) / 2237136896 bytes (2133 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5120m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 62 mods loaded, 62 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                        | Version                  | Source                                             | Signature                                |
	|:----- |:------------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft                 | 1.12.2                   | minecraft.jar                                      | None                                     |
	| LCHI  | mcp                       | 9.42                     | minecraft.jar                                      | None                                     |
	| LCHI  | FML                       | 8.0.99.99                | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge                     | 14.23.5.2854             | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | foamfixcore               | 7.7.4                    | minecraft.jar                                      | None                                     |
	| LCHI  | autoreglib                | 1.3-32                   | AutoRegLib-1.3-32.jar                              | None                                     |
	| LCHI  | baubles                   | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCHI  | bdlib                     | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                       | None                                     |
	| LCHI  | codechickenlib            | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | redstoneflux              | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LCHI  | brandonscore              | 2.4.18                   | BrandonsCore-1.12.2-2.4.18.210-universal.jar       | None                                     |
	| LCHI  | cofhcore                  | 4.6.6                    | CoFHCore-1.12.2-4.6.6.1-universal.jar              | None                                     |
	| LCHI  | cofhworld                 | 1.4.0                    | CoFHWorld-1.12.2-1.4.0.1-universal.jar             | None                                     |
	| LCHI  | controlling               | 3.0.9                    | Controlling-3.0.9.jar                              | None                                     |
	| LCHI  | crafttweaker              | 4.1.20                   | CraftTweaker2-1.12-4.1.20.574.jar                  | None                                     |
	| LCHI  | ctgui                     | 1.0.0                    | CraftTweaker2-1.12-4.1.20.574.jar                  | None                                     |
	| LCHI  | mtlib                     | 3.0.6                    | MTLib-3.0.6.jar                                    | None                                     |
	| LCHI  | modtweaker                | 4.0.18                   | modtweaker-4.0.18.jar                              | None                                     |
	| LCHI  | jei                       | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                          | None                                     |
	| LCHI  | crafttweakerjei           | 2.0.3                    | CraftTweaker2-1.12-4.1.20.574.jar                  | None                                     |
	| LCHI  | ctm                       | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                          | None                                     |
	| LCHI  | cucumber                  | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                          | None                                     |
	| LCHI  | thermalfoundation         | 2.6.7                    | ThermalFoundation-1.12.2-2.6.7.1-universal.jar     | None                                     |
	| LCHI  | draconicevolution         | 2.3.25                   | Draconic-Evolution-1.12.2-2.3.25.351-universal.jar | None                                     |
	| LCHI  | endercore                 | 1.12.2-0.5.76            | EnderCore-1.12.2-0.5.76.jar                        | None                                     |
	| LCHI  | mantle                    | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| LCHI  | tconstruct                | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |
	| LCHI  | extrautils2               | 1.0                      | extrautils2-1.12-1.9.9.jar                         | None                                     |
	| LCHI  | farmingforblockheads      | 3.1.28                   | FarmingForBlockheads_1.12.2-3.1.28.jar             | None                                     |
	| LCHI  | fastleafdecay             | v14                      | FastLeafDecay-v14.jar                              | None                                     |
	| LCHI  | foamfix                   | 0.10.10-1.12.2           | foamfix-0.10.10-1.12.2.jar                         | None                                     |
	| LCHI  | forgelin                  | 1.8.4                    | Forgelin-1.8.4.jar                                 | None                                     |
	| LCHI  | forgemultipartcbe         | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | microblockcbe             | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | None                                     |
	| LCHI  | minecraftmultipartcbe     | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | None                                     |
	| LCHI  | fpsreducer                | mc1.12.2-1.15            | FpsReducer-mc1.12.2-1.15.jar                       | None                                     |
	| LCHI  | guideapi                  | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                        | None                                     |
	| LCHI  | waila                     | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LCHI  | ic2                       | 2.8.220-ex112            | industrialcraft-2-2.8.220-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHI  | mekanism                  | 1.12.2-9.8.3.390         | Mekanism-1.12.2-9.8.3.390.jar                      | None                                     |
	| LCHI  | teslacorelib              | 1.0.17                   | tesla-core-lib-1.12.2-1.0.17.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHI  | industrialforegoing       | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.12.13-237.jar         | None                                     |
	| LCHI  | inventorytweaks           | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHI  | jaopca                    | 1.12.2-2.2.8.103         | JAOPCA-1.12.2-2.2.8.103.jar                        | None                                     |
	| LCHI  | oredictinit               | 1.12.2-2.2.1.71          | JAOPCA-1.12.2-2.2.8.103.jar                        | None                                     |
	| LCHI  | modularmachinery          | 1.11.1                   | modularmachinery-1.12.2-1.11.1.jar                 | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHI  | moreoverlays              | 1.15.1                   | moreoverlays-1.15.1-mc1.12.2.jar                   | None                                     |
	| LCHI  | mrtjpcore                 | 2.1.4.43                 | MrTJPCore-1.12.2-2.1.4.43-universal.jar            | None                                     |
	| LCHI  | harvestcraft              | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zg.jar                    | None                                     |
	| LCHI  | projectred-core           | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-Base.jar               | None                                     |
	| LCHI  | projectred-expansion      | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-mechanical.jar         | None                                     |
	| LCHI  | projectred-relocation     | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-mechanical.jar         | None                                     |
	| LCHI  | projectred-transportation | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-mechanical.jar         | None                                     |
	| LCHI  | psi                       | r1.1-78                  | Psi-r1.1-78.jar                                    | None                                     |
	| LCHI  | rockytweaks               | 0.6.0-PRE-RELEASE-3      | rockytweaks-1.12.2-0.6.0-PRE-RELEASE-3.jar         | None                                     |
	| LCHI  | thaumcraft                | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                   | None                                     |
	| LCHI  | tcinventoryscan           | 2.0.10                   | ThaumicInventoryScanning_1.12.2-2.0.10.jar         | None                                     |
	| LCHI  | thaumicjei                | 1.6.0                    | ThaumicJEI-1.12.2-1.6.0-27.jar                     | None                                     |
	| LCHI  | thermalexpansion          | 5.5.7                    | ThermalExpansion-1.12.2-5.5.7.1-universal.jar      | None                                     |
	| LCHI  | treegrowingsimulator      | 0.0.4                    | TreeGrowingSimulator2017-1.0.1.jar                 | None                                     |
	| LCHI  | teslacorelib_registries   | 1.0.17                   | tesla-core-lib-1.12.2-1.0.17.jar                   | None                                     |
	| LCHE  | wrapup                    | 1.12-1.1.3               | WrapUp-1.12-1.1.3.jar                              | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 419.72' Renderer: 'GeForce GT 740M/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)
		- TinkerDebug (Enabled/Not Forced)

	List of loaded APIs: 
		* Baubles|API (1.4.0.2) from Baubles-1.12-1.5.2.jar
		* cofhapi (2.5.0) from CoFHCore-1.12.2-4.6.6.1-universal.jar
		* ctm-api (0.1.0) from CTM-MC1.12.2-1.0.2.31.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12.2-1.0.2.31.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12.2-1.0.2.31.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12.2-1.0.2.31.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12.2-1.0.2.31.jar
		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.12.2-2.3.25.351-universal.jar
		* farmingforblockheads|api (1.0) from FarmingForBlockheads_1.12.2-3.1.28.jar
		* Guide-API|API (2.0.0) from Guide-API-1.12-2.1.8-63.jar
		* industrialforegoingapi (5) from industrialforegoing-1.12.2-1.12.13-237.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.15.0.291.jar
		* MekanismAPI|core (9.8.1) from Mekanism-1.12.2-9.8.3.390.jar
		* MekanismAPI|energy (9.8.1) from Mekanism-1.12.2-9.8.3.390.jar
		* MekanismAPI|gas (9.8.1) from Mekanism-1.12.2-9.8.3.390.jar
		* MekanismAPI|infuse (9.8.1) from Mekanism-1.12.2-9.8.3.390.jar
		* MekanismAPI|laser (9.8.1) from Mekanism-1.12.2-9.8.3.390.jar
		* MekanismAPI|transmitter (9.8.1) from Mekanism-1.12.2-9.8.3.390.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.12.2-9.8.3.390.jar
		* projectred|api (2.1) from ProjectRed-1.12.2-4.9.4.120-Base.jar
		* PsiAPI (16) from Psi-r1.1-78.jar
		* redstonefluxapi (2.1.1) from RedstoneFlux-1.12-2.1.1.1-universal.jar
		* Thaumcraft|API (6.0.2) from Thaumcraft-1.12.2-6.1.BETA26.jar
		* WailaAPI (1.3) from Hwyla-1.8.26-B41_1.12.2.jar
	[Psi] Active spell: None

**Comment by asd0210a** [comment] 2020-06-22 10:47
@Akay1500 
should be crafttweaker's script problem

**Comment by TheLMiffy1111** [comment] 2022-07-08 09:45
Should be fixed in 2.3.0.0

**Closed as completed by TheLMiffy1111** 2022-07-08 09:45 UTC
Labels: bug
