### ISSUE TITLE
ExtremeReactors compatibility issue at boot

### ISSUE THREAD

**Issue by LemADEC** [TheLMiffy1111/JAOPCA#104] opened 2018-12-26 23:28 UTC
As of ExtremeReactors 1.12.2-0.4.5.50
with JAOPCA 1.12.2-2.2.8.100, an exception is reported at boot:
```
[00:24:40] [Client thread/INFO] [FML]: Holder lookups applied
[00:24:40] [Client thread/INFO] [FML]: Applying holder lookups
[00:24:40] [Client thread/INFO] [FML]: Holder lookups applied
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: java.lang.ClassNotFoundException: erogenousbeef.bigreactors.init.InitHandler
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at java.lang.Class.forName0(Native Method)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at java.lang.Class.forName(Unknown Source)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at thelm.oredictinit.compat.CompatExtremeReactors.register(CompatExtremeReactors.java:19)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at thelm.oredictinit.registry.OreDictRegisCore.initCompat(OreDictRegisCore.java:18)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at thelm.oredictinit.lib.EventHandler.onRegistryWrapUp(EventHandler.java:24)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_37_EventHandler_onRegistryWrapUp_Event0.invoke(.dynamic)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at thelm.wrapup.WrapUp.onVillagerProfessionRegisterLowest(WrapUp.java:97)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_12_WrapUp_onVillagerProfessionRegisterLowest_Register.invoke(.dynamic)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:787)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[00:24:40] [Client thread/INFO] [STDERR]: [thelm.oredictinit.compat.CompatExtremeReactors:register:32]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[00:24:40] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NullPointerException
[00:24:40] [Client thread/INFO] [OreDictInit]: Loading Custom Block Entries
[00:24:40] [Client thread/INFO] [OreDictInit]: Loading Custom Item Entries
[00:24:40] [Client thread/DEBUG] [JAOPCA]: Finding ores
```

Other dependencies used:
WrapUp 1.12-1.1.3
ZeroCore 1.12-0.1.2.3

**Comment by TheLMiffy1111** [comment] 2019-04-03 14:37
duplicate of #44 . will fix

**Closed as completed by TheLMiffy1111** 2019-04-03 14:37 UTC
