### ISSUE TITLE
JAOPCA game crash 

### ISSUE THREAD

**Issue by trilexcom** [TheLMiffy1111/JAOPCA#58] opened 2018-03-26 00:23 UTC
hi Miffy i am getting a game crash regarding JAOPCA can you please tell me if its Modern Metal or Tech Reborn causing this matter? or if its JAOPCA ?

here is the link to crash log : https://pastebin.com/Ab55zfn5

MC : 1.12.2
Forge : 2635
JAOPCA Version : 2.2.6.78

Thanks again Mat

**Comment by TheLMiffy1111** [comment] 2018-03-26 09:07
This is actually a duplicate of #31 , try using NotEnoughIDs

**Closed as completed by TheLMiffy1111** 2018-03-26 09:07 UTC
Labels: duplicate
