### ISSUE TITLE
ANOMALY: meaningless REX prefix used

### ISSUE THREAD

**Issue by iamcarrotmaster** [TheLMiffy1111/JAOPCA#46] opened 2017-12-17 00:55 UTC
I am trying to load this mod with a few other mods in my modpack and at the end of loading it crashes and says some wierd stuff
here is the log file
[2017-12-16-7.log.gz](https://github.com/TheLMiffy1111/JAOPCA/files/1565221/2017-12-16-7.log.gz)
If you need any details im here.

**Comment by TheLMiffy1111** [comment] 2017-12-17 05:12
wrong log i think

**Comment by iamcarrotmaster** [comment] 2017-12-17 14:25
oh sorry here i think
[crash-2017-12-16_18.47.29-client.txt](https://github.com/TheLMiffy1111/JAOPCA/files/1565735/crash-2017-12-16_18.47.29-client.txt)

**Comment by TheLMiffy1111** [comment] 2017-12-18 06:50
Duplicate of #38
Update JAOPCA

**Closed as completed by TheLMiffy1111** 2017-12-18 06:50 UTC
