### ISSUE TITLE
[2.2.8.94] Compatibility Issue with AE2 rev6

### ISSUE THREAD

**Issue by Shandoo94** [TheLMiffy1111/JAOPCA#89] opened 2018-10-09 08:50 UTC
JAOPCA crashes with the new build of AE2

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at thelm.jaopca.api.EnumEntryType.lambda$getRegisterer$12(EnumEntryType.java:115)
	at thelm.jaopca.api.EnumEntryType$$Lambda$1282/1289575659.accept(Unknown Source)
	at thelm.jaopca.registry.RegistryCore.registerEntries(RegistryCore.java:250)
	at thelm.jaopca.registry.RegistryCore.preInit1(RegistryCore.java:77)
	at thelm.jaopca.utils.JAOPCAEventHandler.onRegistryWrapUp(JAOPCAEventHandler.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1653_JAOPCAEventHandler_onRegistryWrapUp_Event2.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at thelm.wrapup.WrapUp.onVillagerProfessionRegisterLowest(WrapUp.java:99)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_946_WrapUp_onVillagerProfessionRegisterLowest_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:762)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at thelm.jaopca.api.EnumEntryType.lambda$getRegisterer$12(EnumEntryType.java:112)
	... 25 more
Caused by: java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:296)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:282)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:115)
	at thelm.jaopca.registry.RegistryCore.registerBlocks(RegistryCore.java:279)
	... 30 more

**Comment by TheLMiffy1111** [comment] 2018-10-10 03:14
Duplicate of #31 .

**Closed as completed by TheLMiffy1111** 2018-10-10 03:14 UTC
