### ISSUE TITLE
[1.12-Crash] Crash on startup with Advanced Rocketry

### ISSUE THREAD

**Issue by gatoborrachon** [TheLMiffy1111/JAOPCA#196] opened 2021-04-05 23:05 UTC
When you try to load Advanced Rocketry and JAOPCA, you will get the following `NoClassDefFoundError` crash: https://pastebin.com/tE8Q0TQL

well, at least tell us how to disable this module, i don't even use the AR crusher.

**Comment by TheLMiffy1111** [comment] 2021-04-06 09:49
Duplicate of #193 , update JAOPCA.

**Closed as completed by TheLMiffy1111** 2021-04-06 09:49 UTC

**Comment by gatoborrachon** [comment] 2021-04-06 14:07
ok, many thanks
