### ISSUE TITLE
Critical Issue with broken Interaction with Nuclearcraft: Overhauled (1.12.2)

### ISSUE THREAD

**Issue by Gitcrafter** [TheLMiffy1111/JAOPCA#246] opened 2022-09-19 17:13 UTC
JAOPCA adds wrong nugget-oredict-tags to seemingly random raidioactive Elements from Nuclearcraft: Overhauled, wich allows for wrong and exploidable recipes for Thermal Expansions Factorizer and the Melter from Nuclearcraft: Overhauled
see the below Screenshots for some examples:

![2022-09-19_19 08 51](https://user-images.githubusercontent.com/81863925/191074239-eb282656-f5dd-431e-88c2-80d7770d2bc4.png)
![2022-09-19_19 09 02](https://user-images.githubusercontent.com/81863925/191074251-500503ec-3c5a-4743-ab56-04abc4fcf927.png)
![2022-09-19_19 09 25](https://user-images.githubusercontent.com/81863925/191074256-35fc34c0-58cb-4570-9280-bc2a5437c857.png)
![2022-09-19_19 09 30](https://user-images.githubusercontent.com/81863925/191074266-be830c34-f7a1-4a16-976d-00e117eac497.png)
![2022-09-19_19 09 42](https://user-images.githubusercontent.com/81863925/191074272-453571df-12b5-47b6-a824-063eee5daa1e.png)
![2022-09-19_19 09 48](https://user-images.githubusercontent.com/81863925/191074281-23d9abc8-32df-4f83-8d06-fe318da2449a.png)
![2022-09-19_19 10 00](https://user-images.githubusercontent.com/81863925/191074291-bedc1ffd-8f4e-4681-9d87-37ab54b95029.png)
![2022-09-19_19 10 04](https://user-images.githubusercontent.com/81863925/191074294-cd5ab2cb-0596-4cda-904c-64db200b300b.png)

**Comment by TheLMiffy1111** [comment] 2022-09-19 17:20
Duplicate of #165 , should already be fixed in 2.2.8.105

**Closed as completed by TheLMiffy1111** 2022-09-19 17:20 UTC

**Comment by Gitcrafter** [comment] 2022-09-19 18:28
Sorry, my bad, I haven´t played with 1.12.2 for over a year and apparently missed a few versions and I also began using the Overhaul version only recently, thank you for clarifying this and sorry for bothering you
